# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 997)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setStyleSheet("background-color: rgb(160, 43, 51)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(50, 30))
        self.label.setMaximumSize(QtCore.QSize(50, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../uacloud_app/img/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("text-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("#frame_3 {border: 0px;}\n"
"\n"
"QFrame {border: 0px solid rgb(158, 159, 159);      /* Light gray border */\n"
"    border-radius: 0px;            /* Rounded corners */}\n"
"\n"
"QPushButton {\n"
"    background-color: #A02B33;  /* Main new color */\n"
"    border: none;               /* No border */\n"
"    color: white;               /* White text color */\n"
"    padding: 8px 15px;         /* Padding around text */\n"
"    font: bold 16px;           /* Bold font with size 16 */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8E2731; /* Slightly darker shade of new color when mouse hovers over */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7C1D25; /* Even darker shade of new color when button is pressed */\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.apps_1 = QtWidgets.QFrame(self.frame_3)
        self.apps_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.apps_1.setStyleSheet("")
        self.apps_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.apps_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.apps_1.setObjectName("apps_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.apps_1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.apps_1)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(self.apps_1)
        self.line_2.setMinimumSize(QtCore.QSize(10, 2))
        font = QtGui.QFont()
        font.setBold(True)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("background-color: rgb(36, 86, 74);\n"
"\n"
" ")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.app1_1 = QtWidgets.QFrame(self.apps_1)
        self.app1_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.app1_1.setStyleSheet("#app1_1 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app1_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_1.setObjectName("app1_1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.app1_1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.app1_1)
        self.label_8.setMaximumSize(QtCore.QSize(150, 150))
        self.label_8.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../uacloud_app/img/apps/1.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_9 = QtWidgets.QLabel(self.app1_1)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.pushButton = QtWidgets.QPushButton(self.app1_1)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.app1_1)
        self.app1_2 = QtWidgets.QFrame(self.apps_1)
        self.app1_2.setStyleSheet("#app1_2 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_2.setObjectName("app1_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.app1_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.app1_2)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(150, 150))
        self.label_10.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../uacloud_app/img/apps/1.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.app1_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_2 = QtWidgets.QPushButton(self.app1_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_11.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.app1_2)
        self.app1_3 = QtWidgets.QFrame(self.apps_1)
        self.app1_3.setStyleSheet("#app1_3 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app1_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_3.setObjectName("app1_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.app1_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.app1_3)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(150, 150))
        self.label_12.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../uacloud_app/img/apps/1.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.app1_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_3 = QtWidgets.QPushButton(self.app1_3)
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_12.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.app1_3)
        self.horizontalLayout_2.addWidget(self.apps_1)
        self.apps_2 = QtWidgets.QFrame(self.frame_3)
        self.apps_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.apps_2.setStyleSheet("\n"
"\n"
"#app1_4 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"#app1_5 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"#app1_6 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"\n"
"")
        self.apps_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.apps_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.apps_2.setObjectName("apps_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.apps_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.apps_2)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter)
        self.line_3 = QtWidgets.QFrame(self.apps_2)
        self.line_3.setMinimumSize(QtCore.QSize(10, 2))
        font = QtGui.QFont()
        font.setBold(True)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("background-color: rgb(36, 86, 74);\n"
"\n"
" ")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_13.addWidget(self.line_3)
        self.app1_4 = QtWidgets.QFrame(self.apps_2)
        self.app1_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.app1_4.setStyleSheet("")
        self.app1_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_4.setObjectName("app1_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.app1_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.app1_4)
        self.label_16.setMaximumSize(QtCore.QSize(150, 150))
        self.label_16.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../uacloud_app/img/apps/1.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_14.addWidget(self.label_16, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_17 = QtWidgets.QLabel(self.app1_4)
        self.label_17.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_4 = QtWidgets.QPushButton(self.app1_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_14.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_13.addWidget(self.app1_4)
        self.app1_5 = QtWidgets.QFrame(self.apps_2)
        self.app1_5.setStyleSheet("#app1_2 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app1_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_5.setObjectName("app1_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.app1_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_18 = QtWidgets.QLabel(self.app1_5)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        self.label_18.setMaximumSize(QtCore.QSize(150, 150))
        self.label_18.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../uacloud_app/img/apps/1.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_15.addWidget(self.label_18, 0, QtCore.Qt.AlignHCenter)
        self.label_19 = QtWidgets.QLabel(self.app1_5)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_15.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_5 = QtWidgets.QPushButton(self.app1_5)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_15.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(self.app1_5)
        self.app1_6 = QtWidgets.QFrame(self.apps_2)
        self.app1_6.setStyleSheet("#app1_3 {border: 1px solid rgb(158, 159, 159);      /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */}\n"
"\n"
"")
        self.app1_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app1_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app1_6.setObjectName("app1_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.app1_6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_20 = QtWidgets.QLabel(self.app1_6)
        self.label_20.setMinimumSize(QtCore.QSize(0, 0))
        self.label_20.setMaximumSize(QtCore.QSize(150, 150))
        self.label_20.setStyleSheet("\n"
"border: 4px;\n"
"border-color:  rgb(102, 255, 139);\n"
"border-radius: 20px;        /* Rounded corners */\n"
"")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("../uacloud_app/img/apps/1.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_16.addWidget(self.label_20, 0, QtCore.Qt.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(self.app1_6)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_6 = QtWidgets.QPushButton(self.app1_6)
        self.pushButton_6.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_16.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(self.app1_6)
        self.horizontalLayout_2.addWidget(self.apps_2)
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.profile_data_frame = QtWidgets.QFrame(self.frame_3)
        self.profile_data_frame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.profile_data_frame.setStyleSheet("\n"
"#profile_data_frame {\n"
"    /* Your styles here */\n"
"    border: 1px solid rgb(158, 159, 159);     /* Light gray border */\n"
"border-radius: 10px;            /* Rounded corners */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.profile_data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_data_frame.setObjectName("profile_data_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.profile_data_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.profile_data_frame)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.profile_picture = QtWidgets.QLabel(self.profile_data_frame)
        self.profile_picture.setMinimumSize(QtCore.QSize(50, 50))
        self.profile_picture.setMaximumSize(QtCore.QSize(150, 150))
        self.profile_picture.setBaseSize(QtCore.QSize(0, 0))
        self.profile_picture.setStyleSheet("#profile_picture {\n"
"    border-radius: 5px;\n"
"}")
        self.profile_picture.setLineWidth(1)
        self.profile_picture.setText("")
        self.profile_picture.setPixmap(QtGui.QPixmap("../uacloud_app/img/profile/1.png"))
        self.profile_picture.setScaledContents(True)
        self.profile_picture.setObjectName("profile_picture")
        self.verticalLayout_7.addWidget(self.profile_picture, 0, QtCore.Qt.AlignHCenter)
        self.frame_16 = QtWidgets.QFrame(self.profile_data_frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_16)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.frame_16)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.frame_16)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_16)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_16)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 0px")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addWidget(self.frame_16)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.profile_data_frame)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; color:#ffffff;\">SPS</span><span style=\" font-size:24pt; color:#ffffff;\">Cloud</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">EXAMENES</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Flappy Bird</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Abrir"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Flappy Bird</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Abrir"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Flappy Bird</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Abrir"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">EXAMENES</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Flappy Bird</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Abrir"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Flappy Bird</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Abrir"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Flappy Bird</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Abrir"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">TIU</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Nombre:"))
        self.label_4.setText(_translate("MainWindow", "Ejemplo"))
        self.label_6.setText(_translate("MainWindow", "Apellidos"))
        self.label_7.setText(_translate("MainWindow", "Ejemplo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
